### ISSUE TITLE
关于旧版卸载问题

### ISSUE THREAD

**Issue by fatevase** [langzhou/note-views-v3#1]
如图，再安装新的v3版本后还存再旧的版本，想去集市里手动删除，但是集市里的已经找不到了。
![挂件中存在旧版](https://user-images.githubusercontent.com/20919830/167237397-253f1074-a568-4fe2-9b71-7b2859ca6a19.png)

请问下如何删除旧版？
![集市中找不到旧版](https://user-images.githubusercontent.com/20919830/167237452-0e37176f-4f34-4891-b0cb-3020dc9a6e16.png)

**Comment by litcu** [comment]
> 如图，再安装新的v3版本后还存再旧的版本，想去集市里手动删除，但是集市里的已经找不到了。 ![挂件中存在旧版](https://user-images.githubusercontent.com/20919830/167237397-253f1074-a568-4fe2-9b71-7b2859ca6a19.png)
> 
> 请问下如何删除旧版？ ![集市中找不到旧版](https://user-images.githubusercontent.com/20919830/167237452-0e37176f-4f34-4891-b0cb-3020dc9a6e16.png)

应该去data/widgets/目录下删除note-view文件夹即可。

**Comment by langzhou** [comment]
> > 如图，再安装新的v3版本后还存再旧的版本，想去集市里手动删除，但是集市里的已经找不到了。 ![挂件中存在旧版](https://user-images.githubusercontent.com/20919830/167237397-253f1074-a568-4fe2-9b71-7b2859ca6a19.png)
> > 请问下如何删除旧版？ ![集市中找不到旧版](https://user-images.githubusercontent.com/20919830/167237452-0e37176f-4f34-4891-b0cb-3020dc9a6e16.png)
> 
> 应该去data/widgets/目录下删除note-view文件夹即可。

bingo
