### ISSUE TITLE
不小心点了属性-全局属性设置里面的移除属性设置

### ISSUE THREAD

**Issue by JCJC01** [langzhou/note-views-v3#3]
不小心点了属性-全局属性设置里面的移除属性设置
重装挂件，也重装了思源笔记，都无法恢复，请问如何回复？

**Comment by langzhou** [comment]
> 不小心点了属性-全局属性设置里面的移除属性设置 重装挂件，也重装了思源笔记，都无法恢复，请问如何回复？

移除的全局属性只需要在属性面板里重新设置该属性名称或类型就会保存的。无法恢复指的是？

**Comment by JCJC01** [comment]
![image](https://user-images.githubusercontent.com/103412730/167383249-15a764e3-16d2-4600-9515-8f051f307f02.png)
谢谢你的kuai's快速回复，如图片，删剩下这些，我想恢复会初始状态，但是搞不了

**Comment by langzhou** [comment]
> ![image](https://user-images.githubusercontent.com/103412730/167383249-15a764e3-16d2-4600-9515-8f051f307f02.png) 谢谢你的kuai's快速回复，如图片，删剩下这些，我想恢复会初始状态，但是搞不了
<img width="524" alt="image" src="https://user-images.githubusercontent.com/6987229/167384307-433e6908-7661-473e-bb24-22d3ff7bc6f8.png">

重新设置展示名称或者属性类型之后呢？

**Comment by JCJC01** [comment]
不懂如何在属性面板设置

**Comment by JCJC01** [comment]
如何新增

**Comment by langzhou** [comment]
> 如何新增

全局属性这里没有手动添加。一般来说你设定了某个属性的名称和类型后，这个属性就会在全局属性中保存，并在其他挂件中共享。

**Comment by JCJC01** [comment]
那，之前的标签属性等，如何恢复？我以为重装思源就一定可以搞掂，结果还是出不来

**Comment by langzhou** [comment]
> 那，之前的标签属性等，如何恢复？我以为重装思源就一定可以搞掂，结果还是出不来

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/6987229/167396475-833fb78d-ac26-45e5-bb03-0f4c10b2ccea.png">
打开开发者工具，把 Noteviews 数据库删除，然后重新载入挂件试试

**Comment by JCJC01** [comment]
谢谢你，按照你说的方法，在开发者工具清除数据后可以了

**Comment by JCJC01** [comment]
![image](https://user-images.githubusercontent.com/103412730/167525266-b3917dea-09a6-4bae-95ab-17d9c0635bdf.png)

如果需要筛选内容块的标签，可以直接将筛选条件设置为：「正文」包含#标签#，而不是将「标签」字段设置为包含 XX；
如图片无法筛选到标签未个人的块，请问是如此使用吗？

**Comment by langzhou** [comment]
> ![image](https://user-images.githubusercontent.com/103412730/167525266-b3917dea-09a6-4bae-95ab-17d9c0635bdf.png)
> 
> 如果需要筛选内容块的标签，可以直接将筛选条件设置为：「正文」包含#标签#，而不是将「标签」字段设置为包含 XX； 如图片无法筛选到标签未个人的块，请问是如此使用吗？

目前你启用的是「子文档」模式，所以出来的笔记都是文档类型（如果有的话），筛选文档类型的标签（tags）直接用标签属性即可。

如果你是用自定义 SQL，查询出来的是普通内容块，那么则需要用「正文」属性检索包含#标签名#。

需要这样分别处理的原因是：思源笔记对文档块和普通内容块的标签处理逻辑是不同的，文档块的标签会存在 tags 这个属性里，但内容块的标签是包含在正文里的。

**Comment by JCJC01** [comment]
但是下拉菜单下面没有可以选文档标签哦
![image](https://user-images.githubusercontent.com/103412730/167526217-ee7ef824-f752-4eb8-8556-ee7d44cc554d.png)

**Comment by langzhou** [comment]
> 但是下拉菜单下面没有可以选文档标签哦 ![image](https://user-images.githubusercontent.com/103412730/167526217-ee7ef824-f752-4eb8-8556-ee7d44cc554d.png)

应该是你的子文档里没有一个设置了标签吧，可以试着添加一个文档标签

**Comment by JCJC01** [comment]
清楚了，之前没有区分文档标签和块标签的区别
请问如果用sql语句，搜索所有标签，应该如何打啊
目前我用的是
![image](https://user-images.githubusercontent.com/103412730/167532632-7cef40da-0418-49a3-acc0-7f041ca7aecf.png)

我试把个人删除好像不行；

**Comment by JCJC01** [comment]
已搞掂
就是没有市集上做得那么漂亮，请问你这个书籍标签是如何实现得？是自己建还是用系统自带得标签？

![image](https://user-images.githubusercontent.com/103412730/167536367-c85d63d3-a654-4784-97f9-5e3ff3558b41.png)

**Comment by langzhou** [comment]
> 已搞掂 就是没有市集上做得那么漂亮，请问你这个书籍标签是如何实现得？是自己建还是用系统自带得标签？
> 
> ![image](https://user-images.githubusercontent.com/103412730/167536367-c85d63d3-a654-4784-97f9-5e3ff3558b41.png)

我加了一个 custom-tags 的自定义属性

**Comment by langzhou** [comment]
> 清楚了，之前没有区分文档标签和块标签的区别 请问如果用sql语句，搜索所有标签，应该如何打啊 目前我用的是 ![image](https://user-images.githubusercontent.com/103412730/167532632-7cef40da-0418-49a3-acc0-7f041ca7aecf.png)
> 
> 我试把个人删除好像不行；

使用建议：SQL 里写核心检索逻辑，不用写的太复杂，其他的 path、标签这些筛选可以用 note views 的属性筛选来过滤

**Comment by JCJC01** [comment]
市集上面版本可以增加吗？自定义属性

**Comment by langzhou** [comment]
> 市集上面版本可以增加吗？自定义属性

<img width="294" alt="image" src="https://user-images.githubusercontent.com/6987229/167546355-1f290d86-25b0-4399-9cbf-baafeae7b9c2.png">
<img width="703" alt="image" src="https://user-images.githubusercontent.com/6987229/167546426-cd9f3daa-3a05-4808-880b-009c612f7268.png">


自定义属性官方的属性面板里就可以加，或者使用 Note Attrs挂件。

**Comment by JCJC01** [comment]
嗯嗯，搭配使用，太棒了，媲美notion 的db，notion感觉就日程筛选的功能牛逼，大佬你这个挂件完全能实现
从早上摸索到现在，基本会用了
我的用途主要是在一个页面内把 to do list写上，然后通过你的挂件汇总后，添加属性（工作，个人，读书，XX项目，未开始，进行中，已完成，放弃）进行管理，并且可以通过用筛选实现分类筛选管理

谢谢上午你sql建议，我主要是抄过来的，不懂；
如果是我要搜页面内的所有block，那应该如何简洁高效地写呢？

**Comment by langzhou** [comment]
> 嗯嗯，搭配使用，太棒了，媲美notion 的db，notion感觉就日程筛选的功能牛逼，大佬你这个挂件完全能实现 从早上摸索到现在，基本会用了 我的用途主要是在一个页面内把 to do list写上，然后通过你的挂件汇总后，添加属性（工作，个人，读书，XX项目，未开始，进行中，已完成，放弃）进行管理，并且可以通过用筛选实现分类筛选管理
> 
> 谢谢上午你sql建议，我主要是抄过来的，不懂； 如果是我要搜页面内的所有block，那应该如何简洁高效地写呢？

Note views 最初的出发点是聚合文档，所以页面内的 blocks 的搜索我暂时没有太多经验哈

**Comment by langzhou** [comment]
> 已查询到如何写了，明天我试试 还是非常谢谢你的挂件，非常好用 请问可以筛选显示图片吗？

可以勾选显示 Markdown 属性，支持图片展示。或者设置属性类型为图片，然后贴入图片地址

**Comment by JCJC01** [comment]
你好，应该是不能直接在note view里直接增加任务或一行的吧
![image](https://user-images.githubusercontent.com/103412730/167771634-65c34f27-536d-446f-b851-02b3585a2001.png)

**Comment by JCJC01** [comment]
大佬，如status属性，我建了几个选项
在筛选时，是否可以调出 选项在里面选呢？这样更快捷？
![Uploading 微信截图_20220511130501.png…]()

**Comment by JCJC01** [comment]
![image](https://user-images.githubusercontent.com/103412730/167773198-8d7c00c9-eee1-4293-aa1e-2d27efa19ef5.png)
图刚才没挂上

**Comment by langzhou** [comment]
> 你好，应该是不能直接在note view里直接增加任务或一行的吧 ![image](https://user-images.githubusercontent.com/103412730/167771634-65c34f27-536d-446f-b851-02b3585a2001.png)

嗯，暂时不支持直接添加行、列

**Comment by langzhou** [comment]
> ![image](https://user-images.githubusercontent.com/103412730/167773198-8d7c00c9-eee1-4293-aa1e-2d27efa19ef5.png) 图刚才没挂上

输入筛选值时会有联想候选词
