### ISSUE TITLE
建议表格和列表视图下的跳转针对行

### ISSUE THREAD

**Issue by winter60** [langzhou/note-views-v3#5]
在表格和列表视图下，鼠标放在整行的任意位置上都可跳转，像卡片视图一样
![image](https://user-images.githubusercontent.com/23653326/167460309-ed3cc45f-3bae-4a50-a419-2dc6469e33d9.png)

**Comment by winter60** [comment]
刚刚看了下，好像表格视图字段好像可以修改，当我没说吧😂

**Comment by langzhou** [comment]
> 刚刚看了下，好像表格视图字段好像可以修改，当我没说吧😂

嗯，目前只有 content 和 title 属性支持跳转，其他的属性是可以编辑的
