### ISSUE TITLE
自定义sql框建议改为多行文本框，方便修改

### ISSUE THREAD

**Issue by winter60** [langzhou/note-views-v3#7]
![image](https://user-images.githubusercontent.com/23653326/167463137-cba37530-ccaf-45bf-92d5-90c33ea1056f.png)

**Comment by langzhou** [comment]
> ![image](https://user-images.githubusercontent.com/23653326/167463137-cba37530-ccaf-45bf-92d5-90c33ea1056f.png)

可以的。
