### ISSUE TITLE
请问如何新增非系统的属性/列？

### ISSUE THREAD

**Issue by tokosmos** [langzhou/note-views-v3#8]
如标题。

今天刚尝试下载了此挂件，但发现所有的属性都是系统属性，不能修改表格的内容。

谢谢！

**Comment by langzhou** [comment]
> 如标题。
> 
> 今天刚尝试下载了此挂件，但发现所有的属性都是系统属性，不能修改表格的内容。
> 
> 谢谢！

<img width="401" alt="image" src="https://user-images.githubusercontent.com/6987229/167649686-45e1d7e9-5f95-4a3f-b769-b6fa7a711a95.png">


1.  通过系统自带的属性面板，一般右键菜单里就能看到；
2. 通过 Note Attrs 挂件可以更加方便的添加文档的自定义属性；
